# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_extrato.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Telas.estilos import Estilos

class Ui_Tela_Extrato(object):
    def __init__(self):
        self.estilo_ext = Estilos()
    def setupUi(self, Ui_Tela_Extrato):
        Ui_Tela_Extrato.setObjectName("Ui_Tela_Extrato")
        Ui_Tela_Extrato.resize(1000, 500)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Ui_Tela_Extrato)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.lbl_ext_usuario = QtWidgets.QLabel(Ui_Tela_Extrato)
        self.lbl_ext_usuario.setStyleSheet("font-weight: bold; font-size: 14px; color: #333333;")
        self.lbl_ext_usuario.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ext_usuario.setObjectName("lbl_ext_usuario")
        self.verticalLayout.addWidget(self.lbl_ext_usuario)
        self.label = QtWidgets.QLabel(Ui_Tela_Extrato)
        self.label.setStyleSheet("font-weight: bold; font-size: 11px; color: #333333;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(Ui_Tela_Extrato)
        self.label_3.setStyleSheet("font-weight: bold; font-size: 11px; color: #6C6C6C;;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(Ui_Tela_Extrato)
        self.pushButton.setStyleSheet("background-color: transparent; color: #333333;font-size: 14px; font-weight: bold; text-align: left;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Assets/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(28, 28))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.list_view_ext_extrato = QtWidgets.QListView(Ui_Tela_Extrato)
        self.list_view_ext_extrato.setStyleSheet("background-color: #6C6C6C; color: white; padding: 5px; corner-radius: 10px; font-size: 14px; font-weight: bold; border-radius: 5px;")
        self.list_view_ext_extrato.setViewMode(QtWidgets.QListView.ListMode)
        self.list_view_ext_extrato.setModelColumn(0)
        self.list_view_ext_extrato.setUniformItemSizes(True)
        self.list_view_ext_extrato.setSelectionRectVisible(False)
        self.list_view_ext_extrato.setItemAlignment(QtCore.Qt.AlignLeading)
        self.list_view_ext_extrato.setObjectName("list_view_ext_extrato")
        self.horizontalLayout_4.addWidget(self.list_view_ext_extrato)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(450, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.btn_ext_encerrar = QtWidgets.QPushButton(Ui_Tela_Extrato)
        self.btn_ext_encerrar.setStyleSheet(self.estilo_ext.estilo_botoes_confirmacao())
        self.btn_ext_encerrar.setObjectName("btn_ext_encerrar")
        self.horizontalLayout_3.addWidget(self.btn_ext_encerrar)
        spacerItem4 = QtWidgets.QSpacerItem(450, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Ui_Tela_Extrato)
        QtCore.QMetaObject.connectSlotsByName(Ui_Tela_Extrato)

    def retranslateUi(self, Ui_Tela_Extrato):
        _translate = QtCore.QCoreApplication.translate
        Ui_Tela_Extrato.setWindowTitle(_translate("Ui_Tela_Extrato", "tela extrato"))
        self.lbl_ext_usuario.setText(_translate("Ui_Tela_Extrato", "Usuario: fulano de tal"))
        self.label.setText(_translate("Ui_Tela_Extrato", "Exibindo Extrato e historico de transferencias, saques, depositos"))
        self.label_3.setText(_translate("Ui_Tela_Extrato", "Atenção ! não esqueça de encerrar a seção clicando no botão \"Encerrar Seção\""))
        self.pushButton.setText(_translate("Ui_Tela_Extrato", "   Extrato da conta"))
        self.btn_ext_encerrar.setText(_translate("Ui_Tela_Extrato", "Encerrar seção"))
