# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_saque.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Telas.estilos import Estilos

class Ui_Tela_Saque(object):

    def __init__(self):
        self.estilo_saque = Estilos()

    def setupUi(self, Ui_Tela_Saque):
        Ui_Tela_Saque.setObjectName("Ui_Tela_Saque")
        Ui_Tela_Saque.resize(1000, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(Ui_Tela_Saque)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem2)
        self.lbl_saque_usuario = QtWidgets.QLabel(Ui_Tela_Saque)
        self.lbl_saque_usuario.setStyleSheet("font-weight: bold; font-size: 14px; color: #333333;")
        self.lbl_saque_usuario.setObjectName("lbl_saque_usuario")
        self.horizontalLayout_21.addWidget(self.lbl_saque_usuario)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem4)
        self.label_7 = QtWidgets.QLabel(Ui_Tela_Saque)
        self.label_7.setStyleSheet("font-weight: bold; font-size: 11px; color: #333333;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_22.addWidget(self.label_7)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_22)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_8.addItem(spacerItem6)
        self.pushButton_10 = QtWidgets.QPushButton(Ui_Tela_Saque)
        self.pushButton_10.setStyleSheet("background-color: transparent; color: #333333;font-size: 12px; font-weight: bold; text-align: left;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Assets/dollar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_8.addWidget(self.pushButton_10)
        self.le_saque_valor = QtWidgets.QLineEdit(Ui_Tela_Saque)
        self.le_saque_valor.setMinimumSize(QtCore.QSize(380, 0))
        self.le_saque_valor.setStyleSheet(self.estilo_saque.estilo_entradas())
        self.le_saque_valor.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.le_saque_valor.setObjectName("le_saque_valor")
        self.verticalLayout_8.addWidget(self.le_saque_valor)
        spacerItem7 = QtWidgets.QSpacerItem(20, 45, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_8.addItem(spacerItem7)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.btn_saque_confirmar = QtWidgets.QPushButton(Ui_Tela_Saque)
        self.btn_saque_confirmar.setStyleSheet(self.estilo_saque.estilo_botoes_confirmacao())
        self.btn_saque_confirmar.setObjectName("btn_saque_confirmar")
        self.horizontalLayout_17.addWidget(self.btn_saque_confirmar)
        self.btn_saque_cancelar = QtWidgets.QPushButton(Ui_Tela_Saque)
        self.btn_saque_cancelar.setStyleSheet(self.estilo_saque.estilo_botoes_cancelamento())
        self.btn_saque_cancelar.setObjectName("btn_saque_cancelar")
        self.horizontalLayout_17.addWidget(self.btn_saque_cancelar)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_15.addLayout(self.verticalLayout_8)
        spacerItem8 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.verticalLayout_6)

        self.retranslateUi(Ui_Tela_Saque)
        QtCore.QMetaObject.connectSlotsByName(Ui_Tela_Saque)

    def retranslateUi(self, Ui_Tela_Saque):
        _translate = QtCore.QCoreApplication.translate
        Ui_Tela_Saque.setWindowTitle(_translate("Ui_Tela_Saque", "Saque"))
        self.lbl_saque_usuario.setText(_translate("Ui_Tela_Saque", "Usuario: fulano de tal"))
        self.label_7.setText(_translate("Ui_Tela_Saque", "Defina o valor que deseja para realizar o saque"))
        self.pushButton_10.setText(_translate("Ui_Tela_Saque", "   Valor do Saque"))
        self.btn_saque_confirmar.setText(_translate("Ui_Tela_Saque", "Confirmar Saque"))
        self.btn_saque_cancelar.setText(_translate("Ui_Tela_Saque", "Cancelar"))
