# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_apresentacao.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela_apresentacao(object):
    def setupUi(self, tela_apresentacao):
        tela_apresentacao.setObjectName("tela_apresentacao")
        tela_apresentacao.resize(1000, 500)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(tela_apresentacao)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.presentation_logo = QtWidgets.QLabel(tela_apresentacao)
        self.presentation_logo.setText("")
        self.presentation_logo.setPixmap(QtGui.QPixmap("./Assets/logo2.png"))
        self.presentation_logo.setScaledContents(False)
        self.presentation_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.presentation_logo.setObjectName("presentation_logo")
        self.verticalLayout.addWidget(self.presentation_logo)
        self.label = QtWidgets.QLabel(tela_apresentacao)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("text-align: center; font-size:18px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(tela_apresentacao)
        self.label_4.setStyleSheet("font-size: 12px; font-weight: bold; color: #737373;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(tela_apresentacao)
        self.label_5.setStyleSheet("font-size: 12px; font-weight: bold; color: #737373;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_2 = QtWidgets.QLabel(tela_apresentacao)
        self.label_2.setStyleSheet("text-align: center; font-size:18px;")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(tela_apresentacao)
        QtCore.QMetaObject.connectSlotsByName(tela_apresentacao)

    def retranslateUi(self, tela_apresentacao):
        _translate = QtCore.QCoreApplication.translate
        tela_apresentacao.setWindowTitle(_translate("tela_apresentacao", "apresentação"))
        self.label.setText(_translate("tela_apresentacao", "Olá! Bem vindo ao banco real"))
        self.label_4.setText(_translate("tela_apresentacao", "Selecione a opção desejada clicando nas opções ao lado."))
        self.label_5.setText(_translate("tela_apresentacao", "Para mais informações, clique na opção ajuda."))
