# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_extrato.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QListWidgetItem
from Telas.estilos import Estilos

class Ui_Tela_Extrato(object):

    def __init__(self):
        self.estilos = Estilos()

    def create_item(self, text):
        item = QListWidgetItem()
        item.setText(text)
        item.setTextAlignment(Qt.AlignHCenter)
        return item

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 500)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.lbl_extr_usuario = QtWidgets.QLabel(Form)
        self.lbl_extr_usuario.setStyleSheet("font-weight: bold; font-size: 14px; color: #333333;")
        self.lbl_extr_usuario.setObjectName("label_2")
        self.verticalLayout.addWidget(self.lbl_extr_usuario, 0, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("color:#333333;font-size:16px;text-alighn:center;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lw_extrato = QtWidgets.QListWidget(Form)
        self.lw_extrato.setStyleSheet("background-color: rgb(108, 108, 108);margin:5px;border-radius: 10px; color: white; font-size: 14px; padding: 5px;\n"
"")
        self.lw_extrato.setObjectName("lw_extrato")
        self.verticalLayout.addWidget(self.lw_extrato)
        self.btn_ext_fechar = QtWidgets.QPushButton(Form)
        self.btn_ext_fechar.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_ext_fechar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_ext_fechar.setStyleSheet(self.estilos.estilo_botoes_cancelamento())
        self.btn_ext_fechar.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.btn_ext_fechar, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_extr_usuario.setText(_translate("Form", "Usuario: fulano de tal"))
        self.label.setText(_translate("Form", "  Extrato"))
        self.btn_ext_fechar.setText(_translate("Form", "Fechar"))